name: Test

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Use node_modules cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: yarn-node-16-lock-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-node-16-lock-
      - run: yarn install --frozen-lockfile
      - run: yarn lint:ci
      - run: yarn test:ci
      - run: yarn build:ci
      # - uses: actions/upload-artifact@v3
      #   with:
      #       name: build-output
      #       path: dist
      #       if-no-files-found: error
      # - run: yarn test:exports
